### ISSUE TITLE
Does satellite.js provide a way to determine if a satellite is above a ground station?

### ISSUE THREAD

**Issue by stupideveloper** [shashwatak/satellite-js#100]
I'm trying to predict when a satellite will cross some coordinates, is there a way to know if it's visible from said coordinates?

Thanks,
Lachlan

**Comment by davidcalhoun** [comment]
Yes!  See the [readme](https://github.com/shashwatak/satellite-js#sample-usage), basically the ground station coordinates is the "observer".  You'd be most interested in computing the "look angles" - azimuth is the compass direction of the satellite from the perspective of the ground station (observer) and elevation is degrees above the horizon (90 degrees is overhead).  Note that elevation above 0 degrees doesn't guarantee that the ground station can connect to the satellite - e.g. mountains or trees on the horizon which obstruct.

**Comment by thkruz** [comment]
@ezze Recommend closing this since the questions has been answered.
