### ISSUE TITLE
TLE Errors - CelesTrak data now at https://celestrak.org

### ISSUE THREAD

**Issue by CelesTrak** [shashwatak/satellite-js#105]
Now that CelesTrak is a non-profit, we have been redirecting all traffic going to other CelesTrak domains (e.g., .com, .net, .space) to [celestrak.org](http://celestrak.org/) (not [www.celestrak.org](http://www.celestrak.org/)). If your software does not handle the standard HTTP 301 response (Moved Permanently), you should change any references to other CelesTrak domains (typically [celestrak.com](http://celestrak.com/) or [www.celestrak.com](http://www.celestrak.com/)) to [celestrak.org](http://celestrak.org/). While using HTTPS is not required, it is highly recommended, to prevent potential future issues.

Also, please note that CelesTrak does not update any data more often than every 2 hours. Processes that check hundreds or thousands of times each day for a specific file or files use limited resources needed to support about a quarter million unique users we see on CelesTrak every day. For orbital data, the 18 SDS data is only updated ~3 times each day (and not all data gets updated each time). The same is true for CelesTrak's SupGP orbital data. Please consider limiting checks to 3-4 times a day to help us all out. Adding checks to limit repeated attempts on an unexpected result (e.g., the HTTP 301 response) can also help us make the most of our resources.

CelesTrak also now supports alternative formats to the TLE format, including CSV and JSON. These are not only easier and more efficient to parse than TLE data, but they also support larger NORAD catalog numbers (and 4-digit years). The current public catalog will run out of 5-digit catalog numbers at 70000 (not 100000), since 70000-99999 are used as 'working space' by 18 SDS. We have already used 3,113 catalog numbers (as of 2022 Jul 15) since going over 50000 on 2021 Dec 13 and increases in things like Starlink launches are likely to accelerate. If you would like more information on these formats, please see our article, "A New Way to Obtain GP Data (aka TLEs)" at https://celestrak.org/NORAD/documentation/gp-data-formats.php.

Our Best,

CelesTrak

**Comment by thkruz** [comment]
@ezze since this isn't an issue with satellite.js, I have [created a page for it in the wiki](https://github.com/shashwatak/satellite-js/wiki/Using-Celestrak) as a reference for new users. Recommend closing this.
