### ISSUE TITLE
Detail units in README

### ISSUE THREAD

**Issue by tempranova** [shashwatak/satellite-js#109]
Hello! I wasn't sure about making an issue for this, but I am working to create a 3D map and wondering what specific unit the "height" measurement is. I get values like 800, etc, but this surely isn't meters? Or is this from some base height that I'm not aware of -- 800 meters is not nearly enough for a satellite in orbit? Thanks!

**Comment by thkruz** [comment]
I assume you figured it out, but for future people's reference, the azimuth and elevation are in radians and the height is in kilometers.
