### ISSUE TITLE
Non-LEO orbits do not properly display

### ISSUE THREAD

**Issue by CelesTrak** [shashwatak/satellite-js#116]
Orbital ring graphics do not properly display for orbits other than LEO.  MEO orbits display as partial arcs and GEO orbits only show dots (see attached image).  

The orbital periods are correct coming out of SGP4 and into satrecs. The issue appears to be a time restriction (~90 mins) somewhere within the graphics potion of the application.  Thus, the LEO orbits display correctly (90 mins), the MEO orbits only show partial arcs (90 mins of a longer period), and GEO orbits (24-hour Period) only show a dot.
![Screen Shot 2022-08-26 at 6 33 55 PM](https://user-images.githubusercontent.com/109627404/225734209-c9375b8d-eed8-4569-9095-37934bb39642.png)

**Comment by thkruz** [comment]
There are no graphics in this library and it only has a propagate function, so anything doing multiple propagate calls (like creating the orbit) are organic to your project or another library. 

You seem to be building on top of cesium. Perhaps this was meant for their repo or another project you used as a starting point?

**Comment by CelesTrak** [comment]
Thanks TK.  

Moved to [Flowm/satvis](https://github.com/Flowm/satvis).   We will keep dialing.
