### ISSUE TITLE
Incorrect Propagation

### ISSUE THREAD

**Issue by scooterjp** [shashwatak/satellite-js#133]
[
    "1 49465U 21105B   21320.80604723 +.00139676 +00000+0 +24680-1 0 99996",
    "2 49465  75.0023 145.0443 0000700 273.0116 101.7429 14.66505288000059"
]

Propagating the following TLE results in eco and geodetic points much higher than its correct altitude.

**Comment by thkruz** [comment]
You are using 3 year old data. You need a much more recent TLE. Anything over 30 days is effectively guessing at best.
