### ISSUE TITLE
Problem getting correct longitude/latitude

### ISSUE THREAD

**Issue by davidcalhoun** [shashwatak/satellite-js#15]
I'm trying to upgrade from an older version of the library to a newer version, and I'm running into an issue where I'm getting strange latitude/longitude values.  From what I can tell, I isolated the issue to satellite.eciToGeodetic.

Here's a reduced test case:

```javascript
// Stubs for a reduced test
var gmst = 5.310370926944962;
var positionEci = {
  x: 1370.4661987034153,
  y: 2426.9993741505536,
  z: -6434.977887390488
};

var positionGd = satellite.eciToGeodetic(positionEci, gmst);

// Actual result:
console.log({
  lat: positionGd.latitude,  // -1.1642744947642691
  lng: positionGd.longitude, // -4.253614852559047
  height: positionGd.height  // 652.5452213255094
});

// Expected result:
// (from http://www.apsalin.com/convert-cartesian-to-geodetic.aspx)
console.log({
  lat: positionGd.latitude,  // -86.7625980501545
  lng: positionGd.longitude, // 60.5476630371258
  height: positionGd.height  // -6350170.45890334
});
```

With my full code, when plotting the values produced by satellite.js I strangely see a miniaturized version of a ground track (ignore the line at the top):
<img width="699" alt="screen shot 2015-07-06 at 3 32 45 pm" src="https://cloud.githubusercontent.com/assets/120596/8534742/48375b62-23f4-11e5-96aa-6691669ea8ae.png">

Am I mixing up coordinate systems or something?  I'm not sure if it's a bug in the library or if I'm going wrong somewhere.

Thanks!

**Comment by davidcalhoun** [comment]
Figured it out - looks like I was missing a step to convert radians back to degrees.

**Comment by ivanstan** [comment]
@davidcalhoun Looks like I'm experiencing the same issue. Can you please provide that missing step?

**Comment by ivanstan** [comment]
I figured it out also, it should be:
```javascript
console.log({
  lat: positionGd.latitude * (180 / Math.PI),
  lng: positionGd.longitude * (180 / Math.PI),
  height: positionGd.height
});

```
