### ISSUE TITLE
Publish satellite.js to npm

### ISSUE THREAD

**Issue by davidcalhoun** [shashwatak/satellite-js#17]
I don't want to claim this package as mine on npmjs.com, but you should publish it there ("npm publish") so folks can satellite.js directly from npm.

Thanks!

**Comment by shashwatak** [comment]
Will do!

**Comment by shashwatak** [comment]
https://www.npmjs.com/package/satellite.js

**Comment by shashwatak** [comment]
Closing, but feel free to reopen if something is broken/incorrect.

**Comment by shashwatak** [comment]
It was cool that I didn't have to add anything, NPM was happy with the package.json that bower used!

**Comment by davidcalhoun** [comment]
Sweet!  Thanks for the quick response.  :)

Now folks can add it just with this: ```npm install satellite.js```
