### ISSUE TITLE
help using with requirejs

### ISSUE THREAD

**Issue by dunko** [shashwatak/satellite-js#18]
Hi there,
I was wondering if anyone could provide me with some newbie instructions, or set me in the right direction using this library with requirejs.

I'm using your example as a main.js and getting an 'amdefine' not defined, if I comment out that if statement, I"m getting a 'define not defined' reference error.

Any help you can offer would be greatly appreciated, I'm just starting out in my first dev job so like I said I'm very much a coming to terms with some understanding JS concepts.

I've been trying this a couple of ways, one using amdefine as per http://requirejs.org/docs/node.html and the other using the define syntax as described under 'Usage' on https://github.com/shashwatak/satellite-js

Any help greatly appreciated
thanks
Duncan

var requirejs = require('requirejs');

if (typeof define !== 'function') {
   var define = require('amdefine')(module,require);
}

define(function(require) {
  var dep = require('dependency');

```
//The value returned from the function is
//    //used as the module export visible to Node.
 return function () {};
```

  });

requirejs.config({
    //Pass the top-level main.js/index.js require
    //    //function to requirejs so that node modules
    //        //are loaded relative to the top-level JS file.
        baseUrl: __dirname,
        nodeRequire: require,
     });

```
      requirejs(['foo', 'bar'],
      function   (foo,   bar) {
             //foo and bar are loaded according to requirejs
                //config, but if not found, then node's require
                  //is used to load the module.
 });
```

module.exports = function () {};
//  Sample TLE
var tleLine1 = '1 25544U 98067A   13149.87225694  .00009369  00000-0  16828-3 0  9031',
    tleLine2 = '2 25544 051.6485 199.1576 0010128 012.7275 352.5669 15.50581403831869';

// Initialize a satellite record
define(['satellite.js/dist/satellite.min.js'], function(satellite) {
var satrec = satellite.twoline2satrec(tleLine1, tleLine2);
});

**Comment by chk1** [comment]
I got it working with this code:
```
<script type="text/javascript" src="scripts/require.js"></script>
<script>
require([
  "scripts/satellite.js/dist/satellite",
], function(satellite){
  console.log(satellite);
  /* your satellite code here */
});
</script>
```

The folder structure is as follows:
```
index.html <-- above code in here
scripts\satellite.js\dist\satellite.js
```

**Comment by thkruz** [comment]
Given how old this issue is, can we close it?

**Comment by dunko** [comment]
Yes please, can close it off, thanks for asking!

**Comment by ezze** [comment]
I created a [repo](https://github.com/solarpatrol/satellite-requirejs) showing a basic usage with Require.js.
Thanks for contribution.
