### ISSUE TITLE
Browserify-friendly

### ISSUE THREAD

**Issue by battlesnake** [shashwatak/satellite-js#22]
I've forked and converted this library to be Browserify-friendly, i.e. I removed RequireJS so now it uses node-like `module.exports` and `require` instead, and thus can be bundled with Browserify.  If this is of interest to you, I can send a pull request.

I also plan to heavily refactor the library in the future, towards a more OO-style, although I'm guessing that this won't be of interest since it will not be backward-compatible at all.

**Comment by shashwatak** [comment]
@battlesnake will making it compatible Browserify break the existing Bower configuration? If not, then please send me a PR =)

While I admire your goal of refactoring the code, I don't recommend you do that without a serious understanding of Orbital Mechanics, Ephemera, and all that good stuff. Besides that, I'm not sure if there is much to be gained by refactoring. The code is actually quite easy to follow from a numerical perspective. You might be able to group together a set of variables and call it a class, but you may find it difficult to draw out groups of variables into separate classes, especially if you don't understand what the variables are.

**Comment by ezze** [comment]
Please consider [this pull request](https://github.com/shashwatak/satellite-js/pull/28).

**Comment by ezze** [comment]
Closing this due to pull request adding Common.js support is merged. @battlesnake, please test whether it's what you want.
