### ISSUE TITLE
How can I calculate heading, velocity and altitude?

### ISSUE THREAD

**Issue by barissaydag** [shashwatak/satellite-js#29]
First of all, thanks a lot for this great library! 

I have a question: I know how to calculate look angle and range. But I need help calculating heading (e.g. 320 degrees), velocity (3 km/s) and altitude (12000 km over ground). How can I achieve these?

Thanks!

**Comment by barissaydag** [comment]
OK, I solved 2 out of 3:
Velocity: sqrt(velocity.x^2 + velocity.y^2 +velocity.z^2);
Altitude: I am converting position to geodetic coordinates and using height property. 

However, I am still stuck with heading. How can I convert velocity.x, y, z to a heading (e.g. 97 degrees east)? 

Thanks a lot and kind regards,
Baris

**Comment by thkruz** [comment]
Could you calculate the lat/long of the next position (ex. position + velocity * 1 sec) and then calculate the heading using that?

**Comment by davidcalhoun** [comment]
@thkruz That's the method I'm using in my project and it works decently well!

The only time it doesn't work well is when the satellite (such as the ISS) is near the poles, where the latitude seems to change very slowly.  In that case you can just do something like calculate the next position + 60 seconds or something.

**Comment by thkruz** [comment]
@davidcalhoun just gotta remember that for polar/sun synchronous satellites, depending on your interval, the +60 sec solution can result in bugs where your latitude at t=0 is 89.98 moving towards the pole and your latitude at t+60 is 89.95 thus giving you an incorrect northern heading at t=0. In that scenario small intervals and no rounding is ideal.

For true geosynchronous - there really isn't a heading in relation to the ground. It does make me wonder if @barissaydag needs to account for the rotation of the earth for their specific project. Your velocity formula finds the speed in space, not in relation to the surface of the earth like your heading.

**Comment by thkruz** [comment]
Recommend closing this if they have no further questions.
