### ISSUE TITLE
Lat/lon only updates every second?

### ISSUE THREAD

**Issue by davidcalhoun** [shashwatak/satellite-js#31]
Thanks for the library!  I've been using it a while and it's really fun to play around with.

I've been experimenting with smoothly animating a satellite's position in realtime.  It seems like the browser is more than capable of computing SGP4 several times per second, but despite that it appears that the lat/lon values only change once per second?

Just was wondering if this is some built in restraint in the SGP4 calculation?

**Comment by davidcalhoun** [comment]
Oh!  I found a way to make it more accurate by including milliseconds in gstime/jday.  Will submit a PR :)

**Comment by ezze** [comment]
Fixed by #38.

**Comment by ezze** [comment]
This is available in 2.0.0 now.
