### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by ezze** [shashwatak/satellite-js#35]
I propose all contributors to follow some Git workflow similar to [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). It will allow to keep `master` branch clean and use it for tagged releases only.

I already created a `develop` branch but not sure whether it should be set as base branch in repository settings. At the moment, `master` branch is a default (base) branch, and all pull requests proposed by other contributors are based to this branch by default. It doesn't fit the proposed workflow and each time contributor creates a pull request he/she should set a base branch of pull request to `develop` manually to follow this workflow. Changing default branch from `master` to `develop` in repository settings can make `develop` branch a default base branch for new pull requests but only @shashwatak is able to change this branch as repo's owner.

What do you think about this, guys?

**Comment by ezze** [comment]
Or we can use `master` branch as development branch (as is at the moment) and create a separate `release` branch for tagged releases. `develop` branch is not required in this case and there is no need for @shashwatak to change the default branch of repository.

**Comment by davidcalhoun** [comment]
Sounds good to me, as long as we add some clear instructions for workflow to the readme.  Not everyone is familiar with it.

**Comment by shashwatak** [comment]
`develop` is now the default branch

**Comment by ezze** [comment]
@shashwatak, thanks a lot for participation! @davidcalhoun, @dangodev, please rebase your pull requests to `develop` branch. guys.

**Comment by ezze** [comment]
Added [Contributing](https://github.com/shashwatak/satellite-js#contributing) section to `README.md`.
