### ISSUE TITLE
Drop Bower support

### ISSUE THREAD

**Issue by ezze** [shashwatak/satellite-js#40]
I think that we should drop Bower support (probably, after version 1.4.0 release of `satellite.js`) as it seems deprecated:

```
$ npm install -g bower
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
/home/ezze/.nvm/versions/node/v6.11.0/bin/bower -> /home/ezze/.nvm/versions/node/v6.11.0/lib/node_modules/bower/bin/bower
/home/ezze/.nvm/versions/node/v6.11.0/lib
└── bower@1.8.2
```

The same depreaction warning is placed on [Bower home page](https://bower.io/) and [Bower Github repo](https://github.com/bower/bower) (there is also an [issue](https://github.com/bower/bower/issues/2298)).

If anybody still uses Bower package of `satellite.js` consider switching to [Yarn](https://yarnpkg.com) or [NPM](https://www.npmjs.com/).

Another reason to drop Bower support is the following: anytime we change the source code of the library we should rebuild everything in `dist` directory including minified file which introduces a big diff even if a change was small. Dropping Bower we can exclude built files in `dist` from the repo.

**Comment by davidcalhoun** [comment]
Sounds good, yeah it's deprecated from what I can tell.

**Comment by ezze** [comment]
Dropped since 2.0.0.
