### ISSUE TITLE
Invalid look angles returned

### ISSUE THREAD

**Issue by jbreed** [shashwatak/satellite-js#41]
Currently having issues getting back valid look angles. Maybe someone can review my code to see the hangup, but as it is right now I am getting azimuth reading of 2.xxxx* and switching around satellites I don't see anything over 5, or 6, degrees. 

**Example Output:** 
azimuth:2.738130998510715
elevation:0.869799331216238
rangeSat:37079.4326120618

**Code example following the readme:**

```
var satrec = sat2.twoline2satrec(thisSat.Line1, thisSat.Line2);
var positionAndVelocity = sat2.propagate(satrec, new Date());
var positionEci = positionAndVelocity.position,
velocityEci = positionAndVelocity.velocity;

var deg2rad = Math.PI / 180;
var observerGd = {
	longitude: -92.000000 * deg2rad,
	latitude:  31.000000 * deg2rad,
	height: 0.302
};
var gmst = sat2.gstime(new Date());
var positionEcf   = sat2.eciToEcf(positionEci, gmst),
	lookAngles    = sat2.ecfToLookAngles(observerGd, positionEcf)

console.log(lookAngles)
```

**Comment by nhamer** [comment]
azimuth is in radians

**Comment by ezze** [comment]
@jbreed, was absence of conversion from radians to degrees the issue in your case?

**Comment by jbreed** [comment]
I haven't looked back at this in a bit. If I recall, many satellites I received spot on AZ and EL except for those that had an inclined orbit.

When I look back at this, I'll be sure to follow up here

**Comment by ezze** [comment]
Feel free to open again.
