### ISSUE TITLE
Used on thehumanitystar.com :)

### ISSUE THREAD

**Issue by davidcalhoun** [shashwatak/satellite-js#42]
Just saw https://www.thehumanitystar.com/ and noticed that they're using `satellite.js`, albeit an older version.  Pretty cool!

Wonder if we should keep track of some cool places where it's being used?

**Comment by Chromework-zz** [comment]
Stuffin.space uses satellite.js as well.

**Comment by thkruz** [comment]
I created a page in the wiki for listing sites that are currently using satellite.js.

Recommend closing this issue.

**Comment by ezze** [comment]
@thkruz, thanks for contribution. I added a link to this wiki page to `README.md`.
