### ISSUE TITLE
misleadingly-named parameter observerCoordsEcf should be observerGeodetic

### ISSUE THREAD

**Issue by nhamer** [shashwatak/satellite-js#44]
nit, documented as observerGeodetic (and Ecf coords don't work as a parameter)

https://github.com/shashwatak/satellite-js/blob/226d8d5520c0cf03a591a6f0bd4ddfd8a1de0965/src/transforms.js#L171

**Comment by ezze** [comment]
@nhamer, thank you for reporting. I made some naming changes [here](https://github.com/shashwatak/satellite-js/commit/77e55d214b14a382275730d1d4b12ad65708b18e). Hope it looks better now.
