### ISSUE TITLE
jday calculations are incorrect for dates older than March 1 1900

### ISSUE THREAD

**Issue by iamthechad** [shashwatak/satellite-js#46]
I'm comparing the `jday` output with http://aa.usno.navy.mil/data/docs/JulianDate.php for some unit test errors I'm seeing in code I'm migrating.

When compared to the algorithm from http://aa.usno.navy.mil/faq/docs/JD_Formula.php, all dates from March 1 1900 to now are correctly converted.

Starting with February 28 1900, all older dates are off by one day. The output from the formula, for example, is 2415077.5 for Feb 28 1900, while the output of `jday` is 2415078.5.

**Comment by thkruz** [comment]
Does it matter if the dates more than 50 years before Sputnik are wrong? It might be indicative of a possible future error in jday, but I don't see what application you would have for modeling satellites 50 years before launch?

**Comment by iamthechad** [comment]
I don't know that we're necessarily plotting satellites with those dates, but since we're already using this library for satellites we're switching over to its `jday` implementation vs our homegrown one. We may or may not have times when we need accurate and old jdays.

**Comment by thkruz** [comment]
This is a fair request, but outside of the scope of what satellite.js aims to accomplish. Unfortunately I am going to close it as `wontfix` and recommend you use another library for astronautical calculations outside the scope of tracking satellites.
