### ISSUE TITLE
vkmpersec Evaluated to Number

### ISSUE THREAD

**Issue by thkruz** [shashwatak/satellite-js#50]
Since vkmpersec is a constant, it should be solved in the code rather than recalculating it when iterating through the whole satellite catalog.

**Comment by thkruz** [comment]
Confirmed VERY minor increase (0.1ms) at the cost of deviating from David Vallado.

**Comment by ezze** [comment]
Moved `vkmpersec` to constants (https://github.com/shashwatak/satellite-js/commit/9d04b6aa0052ac38e1de758a35d1e805c1ece6d7).
