### ISSUE TITLE
Does satellite-js provide a way to see if a sat is in eclipse.

### ISSUE THREAD

**Issue by wgaylord** [shashwatak/satellite-js#51]
I am working on a project and I was wondering if satellite-js provided a function to tell me if a specific satellite is in eclipse or not.

**Comment by wgaylord** [comment]
Anyone know this?

**Comment by davidcalhoun** [comment]
That's an interesting question - my first guess would be to start from the sun's position, and then do a calculation (quadratic search style?) based on that.  You can use a sun position library like this one: https://github.com/mourner/suncalc

**Comment by wgaylord** [comment]
I was asking if the software provided a function for it. I know how its done in libastro used by a python library.

**Comment by thkruz** [comment]
This function is not built into satellite-js.

**Comment by wgaylord** [comment]
So it has ways to see it ifs above the horizon for a observer but not eclipse. Guess its time to start porting parts of libastro to JS so I can supplement this.
