### ISSUE TITLE
What is a good way to determine if satellite is in sunlight?

### ISSUE THREAD

**Issue by pkrasicki** [shashwatak/satellite-js#58]
I need to know if a satellite is illuminated by the sun and possibly be able to estimate its brightness. I read that I would need to calculate phase angle between the satellite, observer and the sun. Does anyone know how to do that?

**Comment by davidcalhoun** [comment]
You can get part of this with a helper like https://github.com/Triggertrap/sun-js, though the times would be slightly different for a satellite because of its altitude.  It may help to peak at some of the math there at least.

**Comment by pkrasicki** [comment]
Thanks for the answer! I've been stuck on this problem for a while. I'm making a free app for spotting the ISS https://github.com/pkrasicki/issviewer. Being able to know if ISS is illuminated is the key to make it usable for observations. It would be nice if satellite.js provided such feature. I'm using SunCalc https://github.com/mourner/suncalc library for getting sunrise/sunset times and position of the sun on the sky.

Unfortunately this is a pure math problem. I've tried using some formulas I found on the internet, but I couldn't get it to work.

**Comment by thkruz** [comment]
Could you use SunCalc.getTimes(date, lat, lng, height) and give it the current altitude of the satellite? Would be like calculating the sunrise/sunset times on a REALLY big mountain.

I am planning work on a similar idea, but for all orbital objects. It seems like that phase angle calculation would be more applicable to celestial bodies that are very large and relatively round, versus satellites that will have varying aspect angles depending on orientation. My plan is to do a rough calculation of 0-100% for how close the satellite is to solar noon and then multiple that by 0-100% for how far away the observer is from solar noon to give you a scale for how optimal it is to look for the satellite right now (ie darkest time on earth vs brightest time for satellite).

Assuming I am not missing something glaring here - you could then iterate that over time to get the ideal times to look for a satellite with a telescope for any lat, lon on earth.

**Comment by thkruz** [comment]
So the major flaw in my idea is that the satellite is changing lat/lon unlike a mountain. New idea is to calculate Ra/Dec for the sun. Convert that into ECI using an arbitrary distance of 1,000,000km. I then iterate calculating the satellites ECI and keeping the minimum distance between the two objects. This allows you to find the time the satellite is MOST in the light over a given interval.

There are definitely better answers, but hopefully it is an option to start with.

**Comment by thkruz** [comment]
Deleted my old comments that were not helpful. Here is the answer you are looking for:

Satellite in Sun Math:
https://www.celestrak.com/columns/v03n01/

Angle Math in 3D:
https://www.geeksforgeeks.org/find-all-angles-of-a-triangle-in-3d/

Dot Math in JS might be useful too:
https://mathjs.org/docs/reference/functions/dot.html

**Comment by pkrasicki** [comment]
That's very helpful! I like this solution, but the problem is that it requires ECI coordinates. I can get them for a satellite from satellite.js. The Earth would be the center I assume? So (0, 0, 0)? The problem is getting ECI coordinates for the sun. SunCalc and sun.js don't seem to give those. SunCalc gives azimuth and elevation.

**Comment by thkruz** [comment]
I calculated the az/el of the sun from lat 0 lon 0 height 0 and then converted it from RAE to ECI. The one gotcha is that you need to do the equations on CelesTrak using the satellite's position as 0,0,0. I just kept everything in ECI and subtracted the satellites position. Take a look at:

satellite.isInSun() in https://github.com/thkruz/keeptrack.space/blob/master/js/lookangles.js
and
sun.getXYZ() in https://github.com/thkruz/keeptrack.space/blob/master/js/sun.js

So far it works perfectly for me. I am sure someone with a degree in this stuff can show you a more efficient way, but its good enough for my purposes.

**Comment by pkrasicki** [comment]
For now I went with @davidcalhoun's idea, because it's easier to implement. It might be less accurate, but so far it's been working pretty well for ISS.

```
// this requires SunCalc from Git master branch. Version 1.8.0 doesn't let you provide the height
function isSunlit(date, lon, lat, heightMeters)
{
	const lonDeg = satellite.radiansToDegrees(lon);
	const latDeg = satellite.radiansToDegrees(lat);
	const sunTimes = SunCalc.getTimes(date, latDeg, lonDeg, heightMeters);

	// get time between sunset start and golden hour. When satellite height is used this time seems to work best
	let sunlightEnd = new Date((sunTimes.sunsetStart.getTime() + sunTimes.goldenHour.getTime()) / 2);
	if (date > sunTimes.dawn && date < sunlightEnd)
		return true;
	else
		return false;
}
```

**Comment by thkruz** [comment]
@ezze Recommend closing this since it has been answered.

**Comment by louisjmorgan** [comment]
this is how I do it using some THREE.js vector methods to simplify the maths:

`const THREE = require('three');

const earthPosition = new THREE.Vector3(0, 0, 0);
const sunPosition = new THREE.Vector3();
const satPosition = new THREE.Vector3();
const sunEarth = new THREE.Vector3();
const sunSat = new THREE.Vector3();

function isEclipsed(satellite, sun) {
  sunPosition.fromArray([sun.x, sun.y, sun.z]);
  satPosition.fromArray([satellite.x, satellite.y, satellite.z]);

  sunEarth.subVectors(earthPosition, sunPosition);
  sunSat.subVectors(satPosition, earthPosition);

  const angle = sunEarth.angleTo(sunSat);

  const sunEarthDistance = sunPosition.distanceTo(earthPosition);
  const sunSatDistance = sunPosition.distanceTo(satPosition);
  const limbAngle = Math.atan2(earthRadius, sunEarthDistance);

  if (angle > limbAngle || sunSatDistance < sunEarthDistance) {
    return false;
  }
  return true;
}
`

**Comment by thkruz** [comment]
I will refer anyone still looking for this to:

https://github.com/thkruz/ootk-core/blob/87529d8326ddc475b51a0e42c61d7ba916ce3fd5/src/body/Sun.ts#L364C3-L388C4 and https://github.com/thkruz/ootk-core/blob/87529d8326ddc475b51a0e42c61d7ba916ce3fd5/src/body/Sun.ts#L493C1-L510C4

Sun calculations are outside the scope of satellite.js, so I am going to close this.
