### ISSUE TITLE
Get a full orbit from -180 to +180

### ISSUE THREAD

**Issue by markov00** [shashwatak/satellite-js#6]
Hi, first I want to thank you for this great library.
I'm using it to display orbits of the ISS and it works great but I'm interested in one specific action: get the exactly the orbit of the ISS starting from a longitude of -180 degree to the longitude of 180 degree starting from an internal timestamp of the orbit.

What I'm doing right now is to get the ISS position at the initial timestamp, then I go back in time for x minutes until the ISS position goes from < 0 to > 0 and than I start from that point to get the full orbit.
It's not a very smart way to get the orbit but it works: the drawback is that an orbit can start e.g. at -178.23 or at -179.34.
Now I'm facing the need to  have the orbit exactly starting at -180 degree: how can I calculate the exact timestamp for that?

Thanks

**Comment by nhamer** [comment]
note that there is no general solution to this problem - some satellites (geosynchronous ones) will ideally never cross -180. others, polar orbits are also not likely to work out well.

what you probably want to implement as a matter of practice, is either n revolutions or a fixed period of time (1 sidereal day is a possibility)

**Comment by thkruz** [comment]
Probably time to close this as well.
