### ISSUE TITLE
Problem with TLE

### ISSUE THREAD

**Issue by markov00** [shashwatak/satellite-js#7]
Hi, I was using this TLE (downloaded from norad http://www.celestrak.com/NORAD/elements/stations.txt ) few in the last days but I can't get the the coordinates, I'm getting NaN as coordinates.

1 25544U 98067A   14329.23485703 -.00026060  00000-0 -42757-3 0  4574
2 25544  51.6461  21.1442 0006610  69.1751  39.9679 15.51409999916316

Is there something wrong with the tle?

**Comment by shashwatak** [comment]
Closing this because it seems like y'all know what's going on =)
