### ISSUE TITLE
can i get venus postion by using SDP4?

### ISSUE THREAD

**Issue by hanchangdong** [shashwatak/satellite-js#70]
In my project, I need to get the position of celestial bodies in real time, for example Venus&Moon&Sun which is in the solar system and Big Dipper which is further away.
Can i use SDP4?
Any suggestions, thank you.

**Comment by thkruz** [comment]
SDP4 is meant for objects with periods > than 225 but definitely within Earth's gravity. That won't work for other celestial bodies. I'd recommend https://github.com/mgreter/ephem.js as a possibility or https://github.com/mourner/suncalc for sun/moon calculations.

**Comment by hanchangdong** [comment]
> SDP4 is meant for objects with periods > than 225 but definitely within Earth's gravity. That won't work for other celestial bodies. I'd recommend https://github.com/mgreter/ephem.js as a possibility or https://github.com/mourner/suncalc for sun/moon calculations.

Thanks a lot!
