### ISSUE TITLE
Typescript definitions are incorrect for gstime function

### ISSUE THREAD

**Issue by iamthechad** [shashwatak/satellite-js#73]
The TypeScript definition for `gstime` is defined as `export function gstime(date: Date): GMSTime;`

This is not correct, since `gstime` can take a `Date`, Julian date (`number`), or any valid params for `jday()`

**Comment by ezze** [comment]
@iamthechad @kylegmaxwell PR is welcome! ;)

**Comment by iamthechad** [comment]
I think I can put something together for this.

**Comment by ezze** [comment]
FIxed in 4.1.1.
