### ISSUE TITLE
TLE Challenge: 0 error, but NaN pos/vel values for 6% of all available TLEs

### ISSUE THREAD

**Issue by owntheweb** [shashwatak/satellite-js#8]
Hello,
I'm making a fun sat sim for a museum project, with satellite-js generating positions for all the satellites. You can see a work-in-progress rendering at:
https://vimeo.com/117338834

Awesome so far, however the video is missing some "dots" due to error-less errors. At the moment, 901 out of the 15116-ish available TLEs (space-track.org) are not producing errors, but are producing NaN values when getting the position and velocity. 

Here's a script with sample TLE to reproduce the issue:

```
//includes (if using node.js)
var fs = require('fs');
eval(fs.readFileSync('satellite.js')+'');
//end includes

//resulting in 0/no error, but also NaN position_and_velocity values
var tle_line_1 = '1 40206U 12008R   15023.55601235 -.00000295  00000-0 -21454-2 0   493';
var tle_line_2 = '2 40206 018.2524 027.2161 7231113 143.1101 300.2726 02.17805022 13667';

//works for reference:
//var tle_line_1 = '1 25544U 98067A   13149.87225694  .00009369  00000-0  16828-3 0  9031';
//var tle_line_2 = '2 25544 051.6485 199.1576 0010128 012.7275 352.5669 15.50581403831869';

var satrec = satellite.twoline2satrec (tle_line_1, tle_line_2);

var now = new Date();

var position_and_velocity = satellite.propagate (satrec,
                                                now.getUTCFullYear(), 
                                                now.getUTCMonth() + 1,
                                                now.getUTCDate(),
                                                now.getUTCHours(), 
                                                now.getUTCMinutes(), 
                                                now.getUTCSeconds());

console.log('error?: ' + satrec.error);
console.log(position_and_velocity);
```

Results:

error?: 0
{ position: { x: NaN, y: NaN, z: NaN },
  velocity: { x: NaN, y: NaN, z: NaN } }

Checking the same in Python, I'm getting different results:

```
from sgp4.earth_gravity import wgs72
from sgp4.io import twoline2rv

l1 = "1 40206U 12008R   15023.55601235 -.00000295  00000-0 -21454-2 0   493"
l2 = "2 40206 018.2524 027.2161 7231113 143.1101 300.2726 02.17805022 13667"

satellite = twoline2rv(l1, l2, wgs72)
position, velocity = satellite.propagate(2014, 1, 2, 7, 5, 52)
print(position)
print(velocity)
print(satellite.error)
```

Results:

[-29081.687479920645, -23277.652884337618, 10048.18022009547]
[0.22139732150168656, -2.094087251764308, 0.6054312911186175]
0

Any thoughts on what I might be doing wrong or if this is an issue that can be looked into? Does the TLE format look alright? 

Thanks for taking a look in advance! :D

**Comment by shashwatak** [comment]
Hi, thanks for making use of this library =)

Sorry for the slow response, been very busy with other stuff.

The fact that the python code is not producing an error means there must be a bug in the javascript, not in your TLE format. I'm not sure if it's how we parse the TLE, or in the math.

I will investigate soon.

**Comment by owntheweb** [comment]
Cool. Thanks for checking in. I truly appreciate it.

Also, thought you might appreciate where I'm going with this longer term, which is why I'm using JavaScript and not Python (not to mention you have some nice add-ons that make transforms easier):
http://christopherstevens.cc/satvr/ (click to move forward, ASWDRF for move - not finished or quite VR friendly just yet)

Thanks again!

**Comment by owntheweb** [comment]
I'll start running through this line by line as soon as I can to see if I can see something. I'll race you? :D

**Comment by shashwatak** [comment]
You've already got a head start haha. Thank you very much =)

**Comment by owntheweb** [comment]
You got it. I'll take a look tomorrow. :smile:

**Comment by owntheweb** [comment]
Still digging in spare time, here's what I've come up with so far:

Using the same TLE info from above, the issue seems to start at the 'bstar' variable, showing up as a NaN value. 
satellite.js line 2317:
```
satrec.bstar        = parseFloat("." + parseInt(longstr1.substring(53, 59), 10) + "E" + longstr1.substring(59, 61));
```

To compare, io.py line 146:
```
satrec.bstar = float(line[53] + '.' + line[54:59])
```

Now, without knowing what's going on just yet, I can fake it and make an adjustment to that js line to get the same value as Python (only testing this TLE example for now - yeah it's ugly):
```
satrec.bstar        = -parseFloat(longstr1.substring(53, 53) + "." + longstr1.substring(54, 59)) * .01;
```

The result is non-NaN position and velocity (yay!), but the position and velocity are still WAY different than what the Python library is returning (*sobs).

I'll continue digging later.

**Comment by owntheweb** [comment]
Sorry in advance it I'm posting too much. I found another, possibly more important item:

For ALL orbiting objects, if there was a NaN result (before making edits in my previous comment), the following was always "-" for line 1:

```
satrec.testChar = longstr1.substring(59, 60);
```

This was the case for 901 orbiting objects at the moment, not updating anything since quite a while. Hmmm....

**Comment by owntheweb** [comment]
Ok, I submitted a pull request that has resolved the issue for 901 of my orbiting objects (no more NaN!)

I'll post a separate ticket if I see anything else as I progress.

**Comment by shashwatak** [comment]
OMG dude, thank you so much =D

I will verify everything works and pull your request ASAP. Please expect
delays =( Life is a bit hectic.

**Comment by owntheweb** [comment]
I understand the hectic. No rush. 

Thanks for sharing this great library! Also, thanks for the opportunity to assist in a small way.

**Comment by shashwatak** [comment]
THANKS! =D
